### ISSUE TITLE
Unable to install with php version < 7

### ISSUE THREAD

**Issue by benediktbecher** [unicodeveloper/laravel-emoji#5]
Unable to install with php version 5.5.1 via composer update

**Comment by unicodeveloper** [comment]
Yeah, you can't because it is specially built for PHP 7 @benediktbecher

**Comment by benediktbecher** [comment]
@unicodeveloper Okay, it was a little bit misleading because PHP 5.4+ was labeled as a requirement in the description.

**Comment by unicodeveloper** [comment]
Sorry about that, I'll change that now @benediktbecher
