### ISSUE TITLE
Characters?

### ISSUE THREAD

**Issue by dotmbf** [unicodeveloper/laravel-emoji#7]
Is this just supposed to show the unicode characters, or an actual emoji, because my app just shows the unicode characters..

**Comment by unicodeveloper** [comment]
What version of PHP are you using? @dominicusdev It's supposed to show actual emojis

**Comment by dotmbf** [comment]
I use PHP 5.6, I have a special version where I have properly downgraded the code.
Can this really be the issue?

**Comment by unicodeveloper** [comment]
Yes, If you are using any version less than PHP 7, you need to add a special hack for it to show actual emojis. This package was designed strictly for PHP 7 because it supports actual emojis out of the box @dominicusdev

**Comment by dotmbf** [comment]
How would my other addons for Laravel function with PHP 7?
Does PHP7 still support PHP5.6 code, or are those functions deprecated?

**Comment by unicodeveloper** [comment]
PHP 7 to a large extent still supports PHP 5.6 code. Personally, all my PHP 5.6 code still worked when I upgraded to PHP 7. If you are unsure/afraid, you can check this [guide](http://php.net/manual/en/migration70.php)

**Comment by dominicusdev** [comment]
Yeah, I just did. I'm trying. Thanks though!

**Comment by dotmbf** [comment]
Shit, cool.. Thanks, works now! :joy:

**Comment by dotmbf** [comment]
So, is there any reason it doesn't get shown as a coloured emoji and just is a few pixels?

**Comment by unicodeveloper** [comment]
coloured emoji?..How does it show?, Can I see a snapshot

**Comment by dotmbf** [comment]
Yeah, http://i.imgur.com/fjRtWxq.png

**Comment by unicodeveloper** [comment]
Wow, it should actually show the colored version?...what operating system and browser are you using?

**Comment by dotmbf** [comment]
I'm currently running Windows 10 and Google Chrome.

**Comment by dotmbf** [comment]
What I want to know is, are they supposed to look like A
Iphone, Samsung or whatever? Or a whole different kind of emoji?

**Comment by unicodeveloper** [comment]
They look different based on the device and platform you are using

**Comment by unicodeveloper** [comment]
Check this out [http://unicode.org/emoji/charts/full-emoji-list.html](http://unicode.org/emoji/charts/full-emoji-list.html). This is how it displays on all the various devices

**Comment by dotmbf** [comment]
Aw, that's sad. Would like to use iPhone's smilies for my application.
