### ISSUE TITLE
Changing Automatically ?

### ISSUE THREAD

**Issue by ahmadyousefdev** [unicodeveloper/laravel-emoji#8]
Hi , Thanks for this amazing package,
is this package converting the emojis automatically?
or should I use `Emoji::findByAlias("Emoji_name")` for each emoji ?

because I want to use it on a textarea and I want it to convert them automatically.. so I just need a clarification :)
thank you

**Comment by unicodeveloper** [comment]
You have to use the findByAlias method

_Best Regards,_

_Otemuyiwa Prosper | Technical Writer | Auth0  auth0.com
https://auth0.com/_
(c) +234-708-909-5645 | @unicodeveloper https://twitter.com/unicodeveloper |
prosper.otemuyiwa1 ( _Skype_ )

**Comment by ahmadyousefdev** [comment]
Thank you 😄
